// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9KjMcpRIu28R-mbQucdzCUDeRZ8_X3Y8',
    appId: '1:5993279988:web:cd850f3057c0eeb60cc9a1',
    messagingSenderId: '5993279988',
    projectId: 'kuza-99aba',
    authDomain: 'kuza-99aba.firebaseapp.com',
    storageBucket: 'kuza-99aba.appspot.com',
    measurementId: 'G-SM1HF068EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJHQvrfDXUYvnR5wnkPswd2cmiRl8ylxM',
    appId: '1:5993279988:android:b631619a735132a50cc9a1',
    messagingSenderId: '5993279988',
    projectId: 'kuza-99aba',
    storageBucket: 'kuza-99aba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAB8Nf8f2lYvoLSAq2MSJMBpTmqQIgTkQ',
    appId: '1:5993279988:ios:b44c625f09bc4ae90cc9a1',
    messagingSenderId: '5993279988',
    projectId: 'kuza-99aba',
    storageBucket: 'kuza-99aba.appspot.com',
    iosBundleId: 'com.example.kuza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAB8Nf8f2lYvoLSAq2MSJMBpTmqQIgTkQ',
    appId: '1:5993279988:ios:6ae3226d9f536b930cc9a1',
    messagingSenderId: '5993279988',
    projectId: 'kuza-99aba',
    storageBucket: 'kuza-99aba.appspot.com',
    iosBundleId: 'com.example.kuza.RunnerTests',
  );
}
